#DataSource
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zhu_blog?useUnicode=true&useSSL=false&characterEncoding=utf8
    username: root
    password: 12345678

